name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Install Kubectl
        uses: azure/setup-kubectl@v1
      - name: Start minikube
        uses: medyagh/setup-minikube@latest
      - name: Start minikube Again for fun
        uses: medyagh/setup-minikube@latest
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Use Docker-Env Feature
        run: | 
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker images
